eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #,http://localhost:8762/eureka,http://localhost:8763/eureka
  instance:
    hostname: 192.168.124.1
    instance-id: 192.168.124.1:8769
spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zll
    password: 12345
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true #显示sql语句
server:
  port: 8769
zuul:
  routes:
    product: /myProduct/**
#     myProduct: #这里随便写 MyProduct/product/list下面的是定位到product/product/list 也可以写成 product: /myProduct/**
#       path: /myProduct/**
#       serviceId: product
